import Foundation
import JobhuntCore
import JobhuntServer
import SwiftData
import SwiftUI

/// Observable container for app-level services, injected into the SwiftUI environment.
/// Constructed once in JobhuntApp and passed via .environment(appServices).
@Observable
final class AppServices: @unchecked Sendable {
    let jobService: JobService
    let siteService: SiteService
    let resumeService: ResumeService
    let queueActor: QueueActor
    let settings: SettingsStore
    let server: JobhuntServer
    let backgroundStore: BackgroundStore
    let toastStore = ToastStore()
    var serverRunning: Bool = false
    var serverError: String?
    /// Long-lived tasks started by `startRuntime()` so `shutdown()` can cancel them (TASK-430).
    private var runtimeTasks: [Task<Void, Never>] = []

    /// Builds the service graph ONLY — no runtime side effects (TASK-425). The HTTP server,
    /// crash recovery, availability checks, and launch observers are started by `startRuntime()`,
    /// which the launch owner calls explicitly for interactive modes. The MCP token is generated by
    /// the launch owner and passed in, so construction never writes to the user's machine.
    ///
    /// - Parameters:
    ///   - mcpToken: token the local server validates MCP requests against ("" when MCP is off).
    ///   - pauseQueue: start the LLM queue paused (UI-test mode keeps seeded `.pending` jobs).
    init(modelContainer: ModelContainer, mcpToken: String, pauseQueue: Bool) {
        let store = BackgroundStore(modelContainer: modelContainer)
        let context = ModelContext(modelContainer)
        let settingsStore = SettingsStore(modelContext: context)
        if pauseQueue {
            settingsStore.llmQueuePaused = true
        }
        let queue = QueueActor(
            store: store,
            isPaused: { await MainActor.run { settingsStore.llmQueuePaused } },
            onSetPaused: { paused in await MainActor.run { settingsStore.llmQueuePaused = paused } },
            readExtractionSettings: { await MainActor.run { settingsStore.extractionSettings() } },
            // Snapshot SettingsStore on the main actor (it's not Sendable); the built provider is
            // Sendable so it crosses back to queue isolation safely (TASK-381).
            providerFactory: { await MainActor.run { LLMProviderFactory.makeProvider(settings: settingsStore) } },
            // TASK-483/512: "configured" = a model is selected AND (for key-requiring providers) a
            // key is present. Shared with the UI's AIConfig via AIReadiness so the queue gate and the
            // setup nudge agree — an empty model now keeps work queued behind the "set up AI" notice
            // instead of running and failing with noModelSelected.
            isProviderConfigured: {
                await MainActor.run { AIReadiness.isConfigured(settingsStore) }
            }
        )
        let js = JobService(store: store, queue: queue)
        let ss = SiteService(store: store)
        let localServer = JobhuntServer(jobService: js, siteService: ss, store: store, mcpToken: mcpToken)
        jobService = js
        siteService = ss
        resumeService = ResumeService(store: store)
        queueActor = queue
        settings = settingsStore
        server = localServer
        backgroundStore = store
    }

    /// Starts runtime services and launch-time side effects: the local HTTP server, LLM-queue crash
    /// recovery, the availability-check loop, and the availability-completion observer. Call once,
    /// from the launch owner, for interactive modes — fixture generation skips this so it never
    /// starts a server or touches user-machine state.
    func startRuntime() {
        let localServer = server
        runtimeTasks.append(Task { @MainActor [weak self] in
            do {
                try await localServer.start()
                self?.serverRunning = true
            } catch {
                self?.serverError = error.localizedDescription
            }
        })
        // Crash recovery: reset requests stuck in "running" back to "queued" and prune old history.
        // One-time data repairs (re-clean captures, backfill request models) are NOT run here — they
        // live in JobhuntMigrator (--reclean / --backfill-models), run out-of-band with the app quit.
        let queue = queueActor
        runtimeTasks.append(Task { @MainActor [weak self] in
            do {
                try await queue.requeueRunningOnLaunch()
                // TASK-383: automatically resume the drain after recovery so requests recovered from
                // a crash (reset running → queued) and any other pending work don't sit idle until a
                // UI action. startProcessing() breaks immediately when the queue is paused, so this
                // respects the user's paused setting.
                await queue.startProcessing()
            } catch {
                // TASK-382: don't swallow crash-recovery failure — running requests would be left
                // stuck with no signal. Surface via the toast (also recorded in the Debug tab's
                // recent-errors log) so the user can re-run the queue.
                NSLog("AppServices: requeueRunningOnLaunch failed: \(error)")
                self?.toastStore.show(
                    "Couldn't recover the LLM queue on launch — some requests may be stuck. \(error.localizedDescription)",
                    isError: true
                )
            }
        })

        // Persist the last-check timestamp through an explicit callback (TASK-428) rather than a
        // global notification observer: the checker hands us the completion time, we write the
        // setting on the main actor.
        let settingsStore = settings
        let store = backgroundStore
        runtimeTasks.append(Task {
            // Run on launch, then re-check hourly (Electron parity: AUTO_AVAILABILITY_INTERVAL_MS).
            // maybeRunStaleCheck gates on the configured interval internally, so this only does real
            // work when a check is actually due — a long-running session no longer stops re-checking.
            while true {
                await AvailabilityChecker.maybeRunStaleCheck(store: store, settings: settingsStore) { date in
                    await MainActor.run {
                        settingsStore.set(
                            ISO8601DateFormatter().string(from: date),
                            forKey: SettingsKey.availabilityLastAutoCheckAt
                        )
                    }
                }
                do { try await Task.sleep(for: .seconds(3600)) } catch { break }
            }
        })
    }

    /// Explicit, app-owned shutdown (TASK-430): cancel runtime tasks and stop the local HTTP server
    /// so the bound port is released. Idempotent — safe to call from a termination hook even if the
    /// server never started. Production relies on this for clean restart/teardown; process exit also
    /// reclaims the port, so it's best-effort on hard termination.
    @MainActor
    func shutdown() async {
        for task in runtimeTasks {
            task.cancel()
        }
        runtimeTasks.removeAll()
        await server.stop()
        serverRunning = false
    }
}
