import Foundation
import JobhuntCore
import JobhuntServer
import SwiftData
import SwiftUI

/// Observable container for app-level services, injected into the SwiftUI environment.
/// Constructed once in JobhuntApp and passed via .environment(appServices).
///
/// `@MainActor`-isolated (TASK-529): the mutable UI-facing state (`serverRunning`, `serverError`) and
/// the non-Sendable `SettingsStore`/`ToastStore`/`runtime` it owns are all main-actor concerns, and the
/// SwiftUI views that read it are already on the main actor. This replaces a blanket
/// `@unchecked Sendable` (which suppressed all isolation checking at the service-composition boundary)
/// with compiler-enforced isolation. The actor-typed services (`JobService`, `QueueActor`,
/// `BackgroundStore`, `SiteService`, `ResumeService`, `JobhuntServer`) are immutable `Sendable` `let`s,
/// so they remain reachable from background contexts without a hop; only `settings`/`toastStore`/UI
/// state require the main actor. QueueActor closures keep snapshotting `SettingsStore` via `MainActor.run`.
@MainActor
@Observable
final class AppServices {
    let jobService: JobService
    let siteService: SiteService
    let resumeService: ResumeService
    let queueActor: QueueActor
    let settings: SettingsStore
    let server: JobhuntServer
    let backgroundStore: BackgroundStore
    let toastStore = ToastStore()
    /// True when this launch generated and wrote an MCP token file, so normal shutdown should delete
    /// it (TASK-530). False when no token was generated (fixture/MAS modes, or a failed write).
    let mcpTokenWasGenerated: Bool
    var serverRunning: Bool = false
    var serverError: String?
    /// Owns the long-lived runtime tasks' lifecycle: idempotent start, and a shutdown that cancels
    /// and AWAITS their exit before stopping the server (TASK-430/554/555/556). Extracted to
    /// JobhuntCore so the invariants are unit-tested (`RuntimeTaskControllerTests`).
    private let runtime = RuntimeTaskController()

    /// Builds the service graph ONLY — no runtime side effects (TASK-425). The HTTP server,
    /// crash recovery, availability checks, and launch observers are started by `startRuntime()`,
    /// which the launch owner calls explicitly for interactive modes. The MCP token is generated by
    /// the launch owner and passed in, so construction never writes to the user's machine.
    ///
    /// - Parameters:
    ///   - mcpToken: token the local server validates MCP requests against ("" when MCP is off).
    ///   - pauseQueue: start the LLM queue paused (UI-test mode keeps seeded `.pending` jobs).
    init(modelContainer: ModelContainer, mcpToken: String, pauseQueue: Bool) {
        let store = BackgroundStore(modelContainer: modelContainer)
        let context = ModelContext(modelContainer)
        let settingsStore = SettingsStore(modelContext: context)
        if pauseQueue {
            settingsStore.llmQueuePaused = true
        }
        let queue = QueueActor(
            store: store,
            isPaused: { await MainActor.run { settingsStore.llmQueuePaused } },
            onSetPaused: { paused in await MainActor.run { settingsStore.llmQueuePaused = paused } },
            readExtractionSettings: { await MainActor.run { settingsStore.extractionSettings() } },
            // Snapshot SettingsStore on the main actor (it's not Sendable); the built provider is
            // Sendable so it crosses back to queue isolation safely (TASK-381).
            providerFactory: { await MainActor.run { LLMProviderFactory.makeProvider(settings: settingsStore) } },
            // TASK-483/512: "configured" = a model is selected AND (for key-requiring providers) a
            // key is present. Shared with the UI's AIConfig via AIReadiness so the queue gate and the
            // setup nudge agree — an empty model now keeps work queued behind the "set up AI" notice
            // instead of running and failing with noModelSelected.
            isProviderConfigured: {
                await MainActor.run { AIReadiness.isConfigured(settingsStore) }
            }
        )
        let js = JobService(store: store, queue: queue)
        let ss = SiteService(store: store)
        let localServer = JobhuntServer(jobService: js, siteService: ss, store: store, mcpToken: mcpToken)
        jobService = js
        siteService = ss
        resumeService = ResumeService(store: store)
        queueActor = queue
        settings = settingsStore
        server = localServer
        backgroundStore = store
        // A non-empty token means generateAndWrite() succeeded this launch and a file exists on disk.
        mcpTokenWasGenerated = !mcpToken.isEmpty
    }

    /// Starts runtime services and launch-time side effects: the local HTTP server, LLM-queue crash
    /// recovery, the availability-check loop, and the availability-completion observer. Call once,
    /// from the launch owner, for interactive modes — fixture generation skips this so it never
    /// starts a server or touches user-machine state.
    @MainActor
    func startRuntime() {
        // Idempotent via RuntimeTaskController: a second call (retry/restart/restore/test) returns
        // without re-running the factory, so it can't spawn duplicate server, crash-recovery, or
        // availability tasks (TASK-556).
        runtime.start {
            var tasks: [Task<Void, Never>] = []

            let localServer = server
            tasks.append(Task { @MainActor [weak self] in
                do {
                    try await localServer.start()
                    self?.serverRunning = true
                } catch {
                    self?.serverError = error.localizedDescription
                }
            })

            // Crash recovery: reset requests stuck in "running" back to "queued" and prune old
            // history. One-time data repairs (re-clean captures, backfill request models) are NOT run
            // here — they live in JobhuntMigrator (--reclean / --backfill-models), run out-of-band.
            let queue = queueActor
            tasks.append(Task { @MainActor [weak self] in
                do {
                    try await queue.requeueRunningOnLaunch()
                    // TASK-383: automatically resume the drain after recovery so requests recovered
                    // from a crash (reset running → queued) and any other pending work don't sit idle
                    // until a UI action. startProcessing() breaks immediately when the queue is
                    // paused, so this respects the user's paused setting.
                    await queue.startProcessing()
                } catch {
                    // TASK-382: don't swallow crash-recovery failure — running requests would be left
                    // stuck with no signal. Surface via the toast (also recorded in the Debug tab's
                    // recent-errors log) so the user can re-run the queue.
                    NSLog("AppServices: requeueRunningOnLaunch failed: \(error)")
                    self?.toastStore.show(
                        "Couldn't recover the LLM queue on launch — some requests may be stuck. " +
                            "\(error.localizedDescription)",
                        isError: true
                    )
                }
            })

            // Persist the last-check timestamp through an explicit callback (TASK-428) rather than a
            // global notification observer: the checker hands us the completion time, we write the
            // setting on the main actor.
            let settingsStore = settings
            let store = backgroundStore
            tasks.append(Task {
                // Run on launch, then re-check hourly (Electron parity: AUTO_AVAILABILITY_INTERVAL_MS).
                // maybeRunStaleCheck gates on the configured interval internally, so this only does
                // real work when a check is actually due — a long session keeps re-checking.
                while true {
                    await AvailabilityChecker.maybeRunStaleCheck(store: store, settings: settingsStore) { date in
                        await MainActor.run {
                            settingsStore.set(
                                ISO8601DateFormatter().string(from: date),
                                forKey: SettingsKey.availabilityLastAutoCheckAt
                            )
                        }
                    }
                    do { try await Task.sleep(for: .seconds(3600)) } catch { break }
                }
            })

            return tasks
        }
    }

    /// Explicit, app-owned shutdown (TASK-430): cancel runtime tasks, wait for them to actually exit,
    /// then stop the local HTTP server so the bound port is released. Idempotent and safe under
    /// repeated/concurrent calls — the task handles are taken synchronously before the first
    /// suspension point, so a second call sees an empty set. Both termination (TASK-554) and
    /// store-restore (TASK-546) rely on this as the quiescing boundary; awaiting task completion
    /// guarantees no background work writes through `BackgroundStore`/`SettingsStore` after shutdown
    /// returns (TASK-555).
    /// The redacted diagnostics blob users copy when reporting an issue (Debug tab and Help → Copy
    /// Diagnostics both call this, so there's one format and one redaction path). Queue counts are
    /// fetched on the store actor; everything else is read on the main actor.
    @MainActor
    func diagnosticsText() async -> String {
        let info = Bundle.main.infoDictionary ?? [:]
        let counts = await (try? backgroundStore.llmQueueCounts())
            ?? LLMQueueCounts(queued: 0, running: 0, failed: 0)
        let recent = toastStore.recentErrors.map {
            DiagnosticsReport.ErrorLine(timestamp: $0.timestamp, message: $0.message)
        }
        return DiagnosticsReport.text(
            appVersion: info["CFBundleShortVersionString"] as? String ?? "unknown",
            buildNumber: info["CFBundleVersion"] as? String ?? "unknown",
            osVersion: ProcessInfo.processInfo.operatingSystemVersionString,
            provider: settings.llmProvider,
            model: settings.llmModel,
            consentGranted: ConsentHelper.isConsented(provider: settings.llmProvider, settings: settings),
            queuePaused: settings.llmQueuePaused,
            serverRunning: serverRunning,
            serverError: serverError,
            queued: counts.queued,
            processing: counts.running,
            failed: counts.failed,
            recentErrors: recent,
            settingsError: settings.lastSettingsError,
            keychainError: settings.keychainWriteError,
            loadError: settings.loadError
        )
    }

    @MainActor
    func shutdown() async {
        // RuntimeTaskController cancels every runtime task and AWAITS its exit before running the
        // finalize step, so no background work (crash recovery, the availability loop) can write
        // through BackgroundStore/SettingsStore after shutdown returns — the quiescing contract both
        // termination (TASK-554) and store-restore (TASK-546) depend on (TASK-555). The availability
        // loop exits immediately when cancelled during its hourly sleep; if cancelled mid-check it
        // finishes that check first (bounded by URLSession timeouts). Idempotent under repeated calls.
        await runtime.shutdown {
            // Cancel + await any kick-initiated queue drain (enqueue/kick/resume) too — the runtime
            // only owns the launch crash-recovery drain, so without this a drain started later by a UI
            // action could still write through the store after shutdown returns (TASK-528).
            await self.queueActor.cancelProcessing()
            await self.server.stop()
        }
        serverRunning = false
    }
}
