import AppKit
import Foundation
import JobhuntCore
import JobhuntServer
import SwiftData
import SwiftUI

/// Observable container for app-level services, injected into the SwiftUI environment.
/// Constructed once in JobhuntApp and passed via .environment(appServices).
///
/// `@MainActor`-isolated (TASK-529): the mutable UI-facing state (`serverRunning`, `serverError`) and
/// the non-Sendable `SettingsStore`/`ToastStore`/`runtime` it owns are all main-actor concerns, and the
/// SwiftUI views that read it are already on the main actor. This replaces a blanket
/// `@unchecked Sendable` (which suppressed all isolation checking at the service-composition boundary)
/// with compiler-enforced isolation. The actor-typed services (`JobService`, `QueueActor`,
/// `BackgroundStore`, `SiteService`, `ResumeService`, `JobhuntServer`) are immutable `Sendable` `let`s,
/// so they remain reachable from background contexts without a hop; only `settings`/`toastStore`/UI
/// state require the main actor. QueueActor closures keep snapshotting `SettingsStore` via `MainActor.run`.
@MainActor
@Observable
final class AppServices {
    let jobService: JobService
    let siteService: SiteService
    let resumeService: ResumeService
    let queueActor: QueueActor
    let settings: SettingsStore
    let server: JobhuntServer
    let backgroundStore: BackgroundStore
    let toastStore = ToastStore()
    /// True when this launch generated and wrote an MCP token file, so normal shutdown should delete
    /// it (TASK-530). False when no token was generated (fixture/MAS modes, or a failed write).
    let mcpTokenWasGenerated: Bool
    /// Set by the launch owner once platform integration exists (TASK-589). Weak, and deliberately
    /// one-directional: the runtime loops need to *post* a notification, and giving AppServices a
    /// strong handle to the object that observes it would be a retain cycle through the app's two
    /// longest-lived types.
    weak var platformIntegration: PlatformIntegration?
    var serverRunning: Bool = false
    var serverError: String?

    /// Postings a check couldn't answer for, and everything the follow-up passes have since found.
    ///
    /// A sweep leaves work behind on purpose — LinkedIn goes twelve per run, a throttled board yields
    /// "don't know" — so without this a posting that closed weeks ago can stay unknown indefinitely,
    /// which is exactly the wasted effort the check exists to prevent. Seeded by any run (the
    /// scheduled sweep or an on-demand one from the Jobs list) and drained by `availabilityDrainTask`.
    var availabilityBacklog = AvailabilityBacklog()
    /// Owns the long-lived runtime tasks' lifecycle: idempotent start, and a shutdown that cancels
    /// and AWAITS their exit before stopping the server (TASK-430/554/555/556). Extracted to
    /// JobhuntCore so the invariants are unit-tested (`RuntimeTaskControllerTests`).
    private let runtime = RuntimeTaskController()

    /// Builds the service graph ONLY — no runtime side effects (TASK-425). The HTTP server,
    /// crash recovery, availability checks, and launch observers are started by `startRuntime()`,
    /// which the launch owner calls explicitly for interactive modes. The MCP token is generated by
    /// the launch owner and passed in, so construction never writes to the user's machine.
    ///
    /// - Parameters:
    ///   - mcpToken: token the local server validates MCP requests against ("" when MCP is off).
    ///   - pauseQueue: start the LLM queue paused (UI-test mode keeps seeded `.pending` jobs).
    init(modelContainer: ModelContainer, mcpToken: String, pauseQueue: Bool) {
        let store = BackgroundStore(modelContainer: modelContainer)
        let context = ModelContext(modelContainer)
        let settingsStore = SettingsStore(modelContext: context)
        if pauseQueue {
            settingsStore.llmQueuePaused = true
        }
        let queue = QueueActor(
            store: store,
            isPaused: { await MainActor.run { settingsStore.llmQueuePaused } },
            // Through `setQueuePaused` so a resume also clears the stored pause reason (TASK-524):
            // a stale "auto-paused after failures" surviving a successful resume would mislabel the
            // user's next deliberate pause. The queue can't say *why* here — the reason is set by the
            // `.autoPaused` / `.authenticationFailed` event handlers, which can.
            onSetPaused: { paused in await MainActor.run { settingsStore.setQueuePaused(paused) } },
            readExtractionSettings: { await MainActor.run { settingsStore.extractionSettings() } },
            // Snapshot SettingsStore on the main actor (it's not Sendable); the built provider is
            // Sendable so it crosses back to queue isolation safely (TASK-381).
            providerFactory: { await MainActor.run { LLMProviderFactory.makeProvider(settings: settingsStore) } },
            // TASK-483/512: "configured" = a model is selected AND (for key-requiring providers) a
            // key is present. Shared with the UI's AIConfig via AIReadiness so the queue gate and the
            // setup nudge agree — an empty model now keeps work queued behind the "set up AI" notice
            // instead of running and failing with noModelSelected.
            isProviderConfigured: {
                await MainActor.run { AIReadiness.isConfigured(settingsStore) }
            }
        )
        let js = JobService(store: store, queue: queue)
        let ss = SiteService(store: store)
        let localServer = JobhuntServer(jobService: js, siteService: ss, store: store, mcpToken: mcpToken)
        jobService = js
        siteService = ss
        resumeService = ResumeService(store: store)
        queueActor = queue
        settings = settingsStore
        server = localServer
        backgroundStore = store
        // A non-empty token means generateAndWrite() succeeded this launch and a file exists on disk.
        mcpTokenWasGenerated = !mcpToken.isEmpty
    }

    /// TASK-590: publish jobs to Spotlight once at launch. A one-shot pass rather than a watcher —
    /// the corpus is a few hundred rows, re-indexing is cheap, and an entry going stale until the
    /// next launch is a far smaller problem than a change-observer firing on every extraction write.
    private func spotlightIndexTask() -> Task<Void, Never> {
        let spotlightStore = backgroundStore
        return Task { @MainActor [weak self] in
            try? await Task.sleep(for: .seconds(5))
            guard !Task.isCancelled, let self else { return }
            // Opt-out (TASK-590): a job search is private enough to be refusable, and without this
            // check "Clear Spotlight Index" only held until the next launch rebuilt the index.
            guard settings.spotlightIndexingEnabled else { return }
            guard let entries = try? await spotlightStore.spotlightEntries() else { return }
            // Replace rather than add, so jobs deleted through a path that doesn't call
            // `SpotlightIndexer.remove` (MCP, the migrator, bulk operations) don't linger as hits
            // that open the app and land on nothing.
            SpotlightIndexer.replaceAll(entries)
        }
    }

    /// TASK-623 #11: the optional end-of-day recap reminder.
    ///
    /// Re-reads the setting each cycle rather than capturing it, so toggling it off takes effect
    /// without a relaunch. Checks every 15 minutes; the target instant comes from
    /// `RecapReminderSchedule`, which is pure so the day-boundary, DST and timezone behaviour (#8) is
    /// testable without waiting a day.
    ///
    /// This loop used to compute the target itself as `hour >= reminderHour`, which left the tested
    /// scheduler unused and fired on the first tick after *every* launch that happened to be past the
    /// hour — quitting and reopening at 20:00 three times meant three "Today's progress"
    /// notifications. A scheduled instant fires once and then moves to tomorrow.
    private func recapReminderTask() -> Task<Void, Never> {
        let recapStore = backgroundStore
        return Task { @MainActor [weak self] in
            guard let self else { return }
            var scheduledHour = settings.dailyRecapReminderHour
            var nextFire = RecapReminderSchedule.nextFireDate(after: Date(), hour: scheduledHour)

            while !Task.isCancelled {
                try? await Task.sleep(for: .seconds(15 * 60))
                guard !Task.isCancelled else { return }

                let hour = settings.dailyRecapReminderHour
                // The user moved the time; re-derive rather than firing against the old target.
                if hour != scheduledHour {
                    scheduledHour = hour
                    nextFire = RecapReminderSchedule.nextFireDate(after: Date(), hour: hour)
                }
                // While it's off, keep the target rolling forward. Otherwise switching it back on in
                // the evening would fire instantly against a target that expired days ago.
                guard settings.dailyRecapReminderEnabled else {
                    if let due = nextFire, Date() >= due {
                        nextFire = RecapReminderSchedule.nextFireDate(after: Date(), hour: hour)
                    }
                    continue
                }
                guard let due = nextFire, Date() >= due else { continue }

                guard let recap = try? await recapStore.todayRecap() else { continue }
                platformIntegration?.notifyDailyRecap(recap)
                nextFire = RecapReminderSchedule.nextFireDate(after: Date(), hour: hour)
            }
        }
    }

    /// Finishes the availability work a sweep deliberately left unfinished, then says so once.
    ///
    /// LinkedIn is checked twelve per run because it throttles bursts, and a throttled or unreachable
    /// ATS board answers "don't know" rather than a verdict. Both are right, and both leave postings
    /// in an unknown state — a check over a few hundred archived jobs can leave sixty. Draining them
    /// by hand means re-running the check six times and reading six dialogs.
    ///
    /// So: small batches at a gentle pace, foreground-only (no fetching on behalf of an app nobody is
    /// looking at), until nothing is left to ask. Then ONE notification with everything found, which
    /// opens the same confirmation sheet a manual check does — nothing is ever expired silently.
    private func availabilityDrainTask() -> Task<Void, Never> {
        let drainStore = backgroundStore
        return Task { @MainActor [weak self] in
            while !Task.isCancelled {
                // Longer than the checker's own pacing: this is the patient pass, and the postings it
                // re-asks about are precisely the ones whose host objected to being asked quickly.
                try? await Task.sleep(for: .seconds(300))
                guard !Task.isCancelled, let self else { return }
                guard settings.bool(forKey: SettingsKey.availabilityAutoCheckEnabled) else { continue }
                guard NSApplication.shared.isActive else { continue }
                guard !availabilityBacklog.isDrained else { continue }

                let batch = availabilityBacklog.nextBatch(limit: AvailabilityBacklog.batchSize)
                guard let jobs = try? await drainStore.jobs(withIDs: batch), !jobs.isEmpty else {
                    // The rows are gone (deleted, or the store moved under us). Nothing to retry, and
                    // spinning on them forever would keep the drain permanently unfinished.
                    availabilityBacklog.absorb(AvailabilitySweep(gone: [], unverified: []))
                    continue
                }

                let sweep = await AvailabilityChecker.findGoneJobsRotating(
                    jobs, settings: settings, restrictToStatuses: nil
                )
                availabilityBacklog.absorb(sweep)
                // The drain reaches jobs the foreground run couldn't, so its conclusions are the
                // freshest ones there are — record them like any other check (TASK-674).
                try? await drainStore.recordAvailabilityOutcomes(sweep.outcomes)

                // Report only when the work is finished and there is something to say. A drain that
                // found nothing stays silent; a partial drain waits until it can give a whole answer.
                if availabilityBacklog.isDrained, availabilityBacklog.hasFindings {
                    platformIntegration?.notifyBacklogDrained(count: availabilityBacklog.gone.count)
                }
            }
        }
    }

    /// TASK-589: follow-ups become due while the app is open; without this they only surface if the
    /// user happens to open Needs Action, which defeats the point of a due date.
    ///
    /// Notified ids are held in memory, not persisted. Re-reminding once per launch is reasonable
    /// for a reminder, and a stored flag would need a migration plus a rule for when to clear it —
    /// the exact stale-flag shape CLAUDE.md warns about.
    private func followUpNotifierTask() -> Task<Void, Never> {
        let followUpStore = backgroundStore
        return Task { @MainActor [weak self] in
            var notified: Set<String> = []
            while !Task.isCancelled {
                // First pass after a short delay rather than immediately: at launch the store is
                // still opening and the user hasn't seen the window yet.
                try? await Task.sleep(for: .seconds(60))
                guard !Task.isCancelled, let self else { return }
                guard let due = try? await followUpStore.dueFollowUps() else { continue }
                if let notification = DueFollowUps.notification(for: due, alreadyNotified: notified) {
                    platformIntegration?.notifyFollowUpsDue(notification)
                    notified.formUnion(notification.coveredIDs)
                }
                try? await Task.sleep(for: .seconds(15 * 60))
            }
        }
    }

    /// Starts runtime services and launch-time side effects: the local HTTP server, LLM-queue crash
    /// recovery, the availability-check loop, and the availability-completion observer. Call once,
    /// from the launch owner, for interactive modes — fixture generation skips this so it never
    /// starts a server or touches user-machine state.
    @MainActor
    func startRuntime() {
        // Idempotent via RuntimeTaskController: a second call (retry/restart/restore/test) returns
        // without re-running the factory, so it can't spawn duplicate server, crash-recovery, or
        // availability tasks (TASK-556).
        runtime.start {
            var tasks: [Task<Void, Never>] = []

            let localServer = server
            tasks.append(Task { @MainActor [weak self] in
                do {
                    try await localServer.start()
                    self?.serverRunning = true
                } catch {
                    self?.serverError = error.localizedDescription
                }
            })

            // Crash recovery: reset requests stuck in "running" back to "queued" and prune old
            // history. One-time data repairs (re-clean captures, backfill request models) are NOT run
            // here — they live in JobhuntMigrator (--reclean / --backfill-models), run out-of-band.
            let queue = queueActor
            tasks.append(Task { @MainActor [weak self] in
                do {
                    try await queue.requeueRunningOnLaunch()
                    // TASK-383: automatically resume the drain after recovery so requests recovered
                    // from a crash (reset running → queued) and any other pending work don't sit idle
                    // until a UI action. startProcessing() breaks immediately when the queue is
                    // paused, so this respects the user's paused setting.
                    await queue.startProcessing()
                } catch {
                    // TASK-382: don't swallow crash-recovery failure — running requests would be left
                    // stuck with no signal. Surface via the toast (also recorded in the Debug tab's
                    // recent-errors log) so the user can re-run the queue.
                    NSLog("AppServices: requeueRunningOnLaunch failed: \(error)")
                    self?.toastStore.show(
                        "Couldn't recover the LLM queue on launch — some requests may be stuck. " +
                            "\(error.localizedDescription)",
                        isError: true
                    )
                }
            })

            // Reap orphaned `running` rows on a timer, not only when a drain happens to run.
            //
            // The orphan that prompted TASK-657 appeared with no drain active and no connection open:
            // the row simply never left `running`. Reaping only at drain start would leave it there
            // until new work arrived, and each orphan permanently leaks a slot from the adaptive
            // concurrency pool — several would throttle the queue toward serial while looking, from
            // the outside, merely slow.
            let reaperQueue = queueActor
            tasks.append(Task {
                while !Task.isCancelled {
                    try? await Task.sleep(for: .seconds(120))
                    guard !Task.isCancelled else { return }
                    _ = try? await reaperQueue.reapOrphanedRunning()
                }
            })

            tasks.append(spotlightIndexTask())
            tasks.append(recapReminderTask())
            tasks.append(followUpNotifierTask())
            tasks.append(availabilityDrainTask())

            // Persist the last-check timestamp through an explicit callback (TASK-428) rather than a
            // global notification observer: the checker hands us the completion time, we write the
            // setting on the main actor.
            let settingsStore = settings
            let store = backgroundStore
            tasks.append(Task {
                // Re-check hourly. Two guardrails on the background pass (the manual "Check
                // Availability" button is unaffected):
                //   • Only run while Jobhunt is FOREGROUND — no fetching for a backgrounded app.
                //   • CONFIRM-FIRST — maybeFindStaleGoneJobs returns candidates without expiring
                //     anything; we surface a single macOS notification (rate-limited to once per 24h)
                //     and let the user confirm which to expire. Nothing changes status silently.
                // maybeFindStaleGoneJobs gates on the configured interval internally, so a long
                // session only does real work when a check is actually due.
                while true {
                    let isForeground = await MainActor.run { NSApplication.shared.isActive }
                    if isForeground {
                        let candidates = await AvailabilityChecker.maybeFindStaleGoneJobs(
                            store: store, settings: settingsStore
                        ) { date in
                            await MainActor.run {
                                // Timestamp setting, never keychain-backed — cannot throw.
                                try? settingsStore.set(
                                    ISO8601DateFormatter().string(from: date),
                                    forKey: SettingsKey.availabilityLastAutoCheckAt
                                )
                            }
                        }
                        if let candidates, !candidates.gone.isEmpty {
                            await MainActor.run {
                                Self.notifyJobsMaybeUnavailable(count: candidates.gone.count, settings: settingsStore)
                            }
                        }
                    }
                    do { try await Task.sleep(for: .seconds(3600)) } catch { break }
                }
            })

            return tasks
        }
    }

    /// Posts the aggregate "jobs may be gone" event for `PlatformIntegration` to turn into a single
    /// macOS notification, rate-limited to at most once per 24h via `availabilityLastNotifiedAt` so a
    /// long foreground session can't spam the user. Main-actor (settings + NotificationCenter).
    private static func notifyJobsMaybeUnavailable(count: Int, settings: SettingsStore) {
        let last = settings.string(forKey: SettingsKey.availabilityLastNotifiedAt)
        if !last.isEmpty, let when = ISO8601DateFormatter().date(from: last),
           Date().timeIntervalSince(when) < 86400 {
            return // already notified within the last 24h
        }
        // Timestamp setting, never keychain-backed — cannot throw.
        try? settings.set(
            ISO8601DateFormatter().string(from: Date()),
            forKey: SettingsKey.availabilityLastNotifiedAt
        )
        NotificationCenter.default.post(
            name: .jobsMaybeUnavailable,
            object: nil,
            userInfo: [JobsMaybeUnavailableKey.count: count]
        )
    }

    /// Explicit, app-owned shutdown (TASK-430): cancel runtime tasks, wait for them to actually exit,
    /// then stop the local HTTP server so the bound port is released. Idempotent and safe under
    /// repeated/concurrent calls — the task handles are taken synchronously before the first
    /// suspension point, so a second call sees an empty set. Both termination (TASK-554) and
    /// store-restore (TASK-546) rely on this as the quiescing boundary; awaiting task completion
    /// guarantees no background work writes through `BackgroundStore`/`SettingsStore` after shutdown
    /// returns (TASK-555).
    /// The redacted diagnostics blob users copy when reporting an issue (Debug tab and Help → Copy
    /// Diagnostics both call this, so there's one format and one redaction path). Queue counts are
    /// fetched on the store actor; everything else is read on the main actor.
    @MainActor
    func diagnosticsText() async -> String {
        let info = Bundle.main.infoDictionary ?? [:]
        let counts = await (try? backgroundStore.llmQueueCounts())
            ?? LLMQueueCounts(queued: 0, running: 0, failed: 0)
        let recent = toastStore.recentErrors.map {
            DiagnosticsReport.ErrorLine(timestamp: $0.timestamp, message: $0.message)
        }
        return DiagnosticsReport.text(
            appVersion: info["CFBundleShortVersionString"] as? String ?? "unknown",
            buildNumber: info["CFBundleVersion"] as? String ?? "unknown",
            osVersion: ProcessInfo.processInfo.operatingSystemVersionString,
            provider: settings.llmProvider,
            model: settings.llmModel,
            consentGranted: ConsentHelper.isConsented(provider: settings.llmProvider, settings: settings),
            queuePaused: settings.llmQueuePaused,
            serverRunning: serverRunning,
            serverError: serverError,
            queued: counts.queued,
            processing: counts.running,
            failed: counts.failed,
            recentErrors: recent,
            settingsError: settings.lastSettingsError,
            keychainError: settings.keychainWriteError,
            loadError: settings.loadError
        )
    }

    @MainActor
    func shutdown() async {
        // RuntimeTaskController cancels every runtime task and AWAITS its exit before running the
        // finalize step, so no background work (crash recovery, the availability loop) can write
        // through BackgroundStore/SettingsStore after shutdown returns — the quiescing contract both
        // termination (TASK-554) and store-restore (TASK-546) depend on (TASK-555). The availability
        // loop exits immediately when cancelled during its hourly sleep; if cancelled mid-check it
        // finishes that check first (bounded by URLSession timeouts). Idempotent under repeated calls.
        await runtime.shutdown {
            // Cancel + await any kick-initiated queue drain (enqueue/kick/resume) too — the runtime
            // only owns the launch crash-recovery drain, so without this a drain started later by a UI
            // action could still write through the store after shutdown returns (TASK-528).
            await self.queueActor.cancelProcessing()
            await self.server.stop()
        }
        serverRunning = false
    }
}
