import AppKit
import JobhuntCore
import SwiftData
import SwiftUI
import UniformTypeIdentifiers

/// Errors raised while resolving a launch mode's store.
enum FixtureOutputError: LocalizedError {
    case refusedProductionPath(String)

    var errorDescription: String? {
        switch self {
        case .refusedProductionPath(let path):
            return "Refusing to seed a fixture to \(path): it resolves to the production store. "
                + "Choose a different --seed-fixture-output path."
        }
    }
}

@main
struct JobhuntApp: App {
    // Non-nil when ModelContainer failed to open — shows recovery UI instead of main window.
    let storeFailure: StoreFailure?

    let modelContainer: ModelContainer?
    let appServices: AppServices?
    let onboardingManager: OnboardingManager?
    let router: Router?
    let platformIntegration: PlatformIntegration?
    let theme = Theme()

    struct StoreFailure {
        let storeURL: URL
        let message: String
    }

    init() {
        do {
            // TASK-426: parse launch arguments into an explicit plan up front. Invalid/incomplete
            // arguments throw (caught below) instead of silently falling back to production.
            let plan = try LaunchPlan.parse(CommandLine.arguments)

            let container = try Self.openStore(for: plan.mode)

            // TASK-425/426: the MCP token is generated by the launch owner (here), gated by mode,
            // and passed into the service graph — construction no longer writes to the machine.
            var mcpToken = ""
            if plan.needsMCPToken {
                #if !MAS_BUILD
                do {
                    mcpToken = try MCPTokenManager.generateAndWrite()
                } catch {
                    NSLog("JobhuntApp: MCP token setup failed — MCP will be unavailable: \(error)")
                }
                #endif
            }

            modelContainer = container
            let services = AppServices(
                modelContainer: container,
                mcpToken: mcpToken,
                pauseQueue: plan.startsQueuePaused
            )
            appServices = services
            let mgr = OnboardingManager(settings: services.settings)
            if plan.mode == .uiTest { mgr.isPresented = false }  // Never block tests with onboarding
            onboardingManager = mgr
            let sharedRouter = Router()
            router = sharedRouter
            let integration = PlatformIntegration(router: sharedRouter, modelContainer: container)
            platformIntegration = integration
            storeFailure = nil

            Task { @MainActor in
                // Interactive modes start runtime services AND platform integration (which requests
                // notification auth, registers focus/deep-link observers, applies window policy).
                // Fixture generation does none of this — it only seeds and exits (TASK-419/425).
                if plan.runsRuntimeServices {
                    integration.start(queue: services.queueActor)
                    services.startRuntime()
                }
                if plan.allowsDemoSeed {
                    try? await DemoSeeder.seedDemo(into: services.backgroundStore)
                } else if plan.seedDemoDataRequested {
                    // TASK-427: a seed flag outside UI-test mode must not touch the selected store.
                    fputs("Refusing --seed-demo-data without --ui-test-store: demo seeding is only "
                        + "allowed into the isolated UI-test store, not the selected store.\n", stderr)
                }
                if case .fixtureGenerate = plan.mode {
                    do {
                        // TASK-423: fail (don't silently no-op) if the target already has data — a
                        // fixture seeded on top of existing rows would be stale/incomplete.
                        let existing = try await services.backgroundStore.fetch(FetchDescriptor<Job>())
                        guard existing.isEmpty else {
                            fputs("Fixture output target already contains \(existing.count) job(s) — "
                                + "refusing to seed onto a non-empty store. Remove it first.\n", stderr)
                            exit(1)
                        }
                        try await FixtureSeeder.seed(into: services.backgroundStore, skipIfPopulated: false)
                        exit(0)
                    } catch {
                        fputs("FixtureSeeder failed: \(error)\n", stderr)
                        exit(1)
                    }
                }
            }
        } catch {
            modelContainer = nil
            appServices = nil
            onboardingManager = nil
            router = nil
            platformIntegration = nil
            // Clear message for launch-argument errors; localizedDescription otherwise.
            let message = (error as? LaunchArgumentError)?.description ?? error.localizedDescription
            storeFailure = StoreFailure(
                storeURL: ModelContainerFactory.productionStoreURL(),
                message: message
            )
        }
    }

    /// Opens the ModelContainer for the given launch mode. Store-selection policy lives here, one
    /// branch per mode, instead of interleaved conditionals in `init` (TASK-426).
    private static func openStore(for mode: LaunchMode) throws -> ModelContainer {
        switch mode {
        case .uiTest:
            // Dedicated temp store that cannot touch the user's production database.
            let storeURL = URL(fileURLWithPath: NSTemporaryDirectory())
                .appendingPathComponent("JobhuntUITest/jobhunt-ui-test.store")
            try? FileManager.default.createDirectory(
                at: storeURL.deletingLastPathComponent(), withIntermediateDirectories: true)
            // Always start fresh so tests see a clean slate.
            let shmURL = storeURL.appendingPathExtension("shm")
            let walURL = storeURL.appendingPathExtension("wal")
            for url in [storeURL, shmURL, walURL] { try? FileManager.default.removeItem(at: url) }
            return try ModelContainerFactory.test(at: storeURL)
        case .fixtureRead(let path):
            // Open an isolated copy of a committed fixture database.
            return try ModelContainerFactory.fixture(copying: URL(fileURLWithPath: path))
        case .fixtureGenerate(let outputPath):
            // Seed a fresh fixture and write it to the given path (used by build-fixture-db.sh).
            // TASK-423: never let fixture generation overwrite the user's production store.
            guard LaunchPolicy.isSafeFixtureOutputPath(
                outputPath,
                productionStorePath: ModelContainerFactory.productionStoreURL().path
            ) else {
                throw FixtureOutputError.refusedProductionPath(outputPath)
            }
            let outputURL = URL(fileURLWithPath: outputPath)
            try? FileManager.default.createDirectory(
                at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true)
            return try ModelContainerFactory.test(at: outputURL)
        case .production:
            return try ModelContainerFactory.production()
        }
    }

    var body: some Scene {
        WindowGroup {
            if let failure = storeFailure {
                StoreRecoveryView(failure: failure)
            } else if let container = modelContainer,
                      let services = appServices,
                      let mgr = onboardingManager,
                      let r = router,
                      let integration = platformIntegration {
                ContentView(router: r, theme: theme)
                    .environment(services)
                    .sheet(isPresented: Binding(
                        get: { mgr.isPresented },
                        set: { mgr.isPresented = $0 }
                    )) {
                        OnboardingView(
                            onboardingManager: mgr,
                            settings: services.settings,
                            modelContainer: container,
                            resumeService: services.resumeService
                        )
                    }
                    .onOpenURL { url in
                        integration.handleDeepLink(url)
                    }
                    .modelContainer(container)
            }
        }
        .defaultSize(width: 1200, height: 750)
        .commands {
            if let r = router, let services = appServices, let container = modelContainer {
                QueueMenuCommands()
                QualityMenuCommands()

                // Go menu — jump to any section via ⌃⌘<n>. A standard macOS navigation
                // affordance, and the deterministic path UI tests use (synthesized clicks on
                // the List(.sidebar) rows are unreliable under XCUITest on macOS 26).
                CommandMenu("Go") {
                    Button("Dashboard") { r.navigateToSection(.dashboard) }
                        .keyboardShortcut("1", modifiers: [.command, .control])
                    Button("Needs Action") { r.navigateToSection(.needsAction) }
                        .keyboardShortcut("2", modifiers: [.command, .control])
                    Button("Jobs") {
                        r.activeSavedSearchID = nil
                        r.sidebarJobFilter = nil
                        r.navigateToSection(.jobs)
                    }
                    .keyboardShortcut("3", modifiers: [.command, .control])
                    Button("Sites") { r.navigateToSection(.sites) }
                        .keyboardShortcut("4", modifiers: [.command, .control])
                    Button("Duplicates") { r.navigateToSection(.duplicates) }
                        .keyboardShortcut("5", modifiers: [.command, .control])
                    Button("LLM Queue") { r.navigateToSection(.llmQueue) }
                        .keyboardShortcut("6", modifiers: [.command, .control])
                    Button("Data Quality") { r.navigateToSection(.dataQuality) }
                        .keyboardShortcut("7", modifiers: [.command, .control])
                    Divider()
                    Button("Settings") { r.navigateToSection(.settings) }
                        .keyboardShortcut("8", modifiers: [.command, .control])
                }

                // ⌘N — Add Job (HIG-7)
                CommandGroup(replacing: .newItem) {
                    Button("Add Job…") {
                        r.navigateToSection(.jobs)
                        r.showAddJobSheet = true
                    }
                    .keyboardShortcut("n", modifiers: .command)
                }

                // ⌘K — Jump to Jobs / focus search
                CommandGroup(after: .newItem) {
                    Button("Search Jobs") {
                        r.navigateToSection(.jobs)
                        r.focusSearch = true
                    }
                    .keyboardShortcut("k", modifiers: .command)
                }

                // ⌘⇧E — Export job list fields to CSV (not a full backup; HIG-18)
                CommandGroup(after: .importExport) {
                    Button("Export Job List to CSV…") {
                        Task { @MainActor in
                            let ctx = ModelContext(container)
                            // TASK-377: don't let a fetch failure produce a valid-looking empty CSV —
                            // surface it and abort instead of falling back to an empty job list.
                            let jobs: [Job]
                            do {
                                jobs = try ctx.fetch(FetchDescriptor<Job>(
                                    sortBy: [SortDescriptor(\Job.createdAt, order: .reverse)]
                                ))
                            } catch {
                                services.toastStore.show(
                                    "Couldn't read jobs for export: \(error.localizedDescription)", isError: true
                                )
                                return
                            }
                            let csv = ExportService.jobsCSV(jobs: jobs)
                            let panel = NSSavePanel()
                            panel.allowedContentTypes = [.commaSeparatedText]
                            panel.nameFieldStringValue = "jobs.csv"
                            guard panel.runModal() == .OK, let url = panel.url else { return }
                            do {
                                try ExportService.write(csv, to: url)
                            } catch {
                                services.toastStore.show(
                                    "Export failed: \(error.localizedDescription)", isError: true
                                )
                            }
                        }
                    }
                    .keyboardShortcut("e", modifiers: [.command, .shift])
                }

                #if !MAS_BUILD
                    CommandGroup(after: .appInfo) {
                        Button("Check for Updates…") {
                            SparkleUpdater.checkForUpdates()
                        }
                    }
                #endif
            }
        }

        // HIG-2: Dedicated Settings scene — opened via ⌘, from the app menu.
        // Only available when the store opened successfully.
        Settings {
            if let services = appServices, let container = modelContainer {
                SettingsView()
                    .environment(services)
                    .environment(theme)
                    .modelContainer(container)
            }
        }
    }
}
